<a href="https://colab.research.google.com/github/beyzadurdu6619/ML/blob/main/LinearRegression_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [81]:
df=pd.read_csv('student.csv')

In [ ]:
df.head(5)

   Hours Studied  ...  Performance Index
0              7  ...               91.0
1              4  ...               65.0
2              8  ...               45.0
3              5  ...               36.0
4              7  ...               66.0

[5 rows x 6 columns]

In [ ]:
df=pd.get_dummies(df,columns=['Extracurricular Activities'],drop_first=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Sleep Hours                       10000 non-null  int64
 3   Sample Question Papers Practiced  10000 non-null  int64
 4   Performance Index                 10000 non-null  float64
 5   Extracurricular Activities_Yes    10000 non-null  bool
dtypes: bool(1), float64(1), int64(4)
memory usage: 400.5 KB

In [ ]:
df['Performance Index']=df['Performance Index'].astype(int)
df.head(3)

   Hours Studied  ...  Extracurricular Activities_Yes
0              7  ...                            True
1              4  ...                           False
2              8  ...                            True

[3 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Sleep Hours                       10000 non-null  int64
 3   Sample Question Papers Practiced  10000 non-null  int64
 4   Performance Index                 10000 non-null  int64
 5   Extracurricular Activities_Yes    10000 non-null  bool
dtypes: bool(1), int64(5)
memory usage: 400.5 KB

In [ ]:
y=df['Performance Index']
x=df.drop('Performance Index',axis=1)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
df.head(3)

   Hours Studied  ...  Extracurricular Activities_Yes
0              7  ...                            True
1              4  ...                           False
2              8  ...                            True

[3 rows x 6 columns]

In [ ]:
l=LinearRegression()
model=l.fit(x_train,y_train)

In [82]:
model.predict([[10,60,8,3,1]])

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([60.6218279])

In [85]:
x1=model.score(x_test,y_test)

In [86]:
x2=model.score(x_train,y_train)

In [87]:
son=x1-x2
print(son)

0.0002934118890790538